name: Auto Deployment to S3 bucket

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - 26-githubactions

jobs:
  build-and-deploy:
    name:
    runs-on: ubuntu-18.04
    steps:
      - name: Checkout source code.
        uses: actions/checkout@v2

      - name: node_modules caching
        uses: actions/cache@v2
        with:
          path: ./slack-clone-client/node_modules
          key: ${{ runner.OS }}-build-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.OS }}-build-client
            ${{ runner.OS }}-client

      - name: install dependency
        run: npm install
        working-directory: ./slack-clone-client

      - name: create env file
        run: |
          touch .env.production
          echo REACT_APP_GOOGLE_CLIENT_ID=${{ secrets.REACT_APP_GOOGLE_CLIENT_ID }} >> .env.production
          echo REACT_APP_ENDPOINT=${{ secrets.REACT_APP_ENDPOINT }} >> .env.production
          cat .env.production
        working-directory: ./slack-clone-client

      - name: build project
        run: npm run build:production
        working-directory: ./slack-clone-client
        env:
          CI: false

      - name: Deploy S3 bucket
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_S3_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_S3_SECRET_ACCESS_KEY }}
        run: |
          aws s3 cp \
            --recursive \
            --region ap-northeast-2 \
            build s3://the-slack # 자신의 레포지토리로 변경해주세요.
